#ifndef COMMON_TYPE_H
#define COMMON_TYPE_H

typedef enum {
    STATUS_SUCCESS = 0,
    STATUS_FAILURE = 1,
    STATUS_OUT_OF_MEMORY = 2,
    STATUS_INVALID_ARGUMENT = 3,
    STATUS_FILE_NOT_FOUND = 4,
    STATUS_FILE_INVALID = 5,
    STATUS_FILE_ALREADY_EXISTS = 6,
    STATUS_NOT_IMPLEMENTED = 7,
    STATUS_TIMEOUT = 8,
    STATUS_BUSY = 9,
    STATUS_NOT_SUPPORTED = 10,
    STATUS_INVALID_OPERATION = 11,
    STATUS_NOT_INITIALIZED = 12,
    STATUS_ALREADY_INITIALIZED = 13,
    STATUS_INVALID_STATE = 14,
    STATUS_NOT_FOUND = 15,
    STATUS_ABORTED = 16,
    STATUS_IO_ERROR = 17,
    STATUS_FILE_CORRUPTED = 18
} status_t;

#endif /* COMMON_TYPE_H */
