/**
 * @file wl_layer.h
 * @author Le Duc Son
 * @date 2026-07-02
 * @brief ESP-IDF Wear Levelling (WL) translation layer - read support
 * @details
 * FATFS partitions generated by ESP-IDF (storage.bin dumps) are wrapped in a
 * wear-levelling layer. The raw partition layout is:
 *
 *   +--------------------------------------------------+ 0x0
 *   |  Data pages (page_size each, usually 4096 B)     |
 *   |  ... logical FAT volume, rotated by WL ...       |
 *   +--------------------------------------------------+ addr_state1
 *   |  wl_state copy 1 (64 B header + pos records)     |
 *   +--------------------------------------------------+ addr_state2
 *   |  wl_state copy 2 (identical mirror)              |
 *   +--------------------------------------------------+ addr_cfg
 *   |  wl_config (36 B, CRC32 protected)               |
 *   +--------------------------------------------------+ full_mem_size
 *
 * Logical sector 0 (the FAT boot sector) is therefore NOT at physical
 * offset 0. The mapping is:
 *
 *   phys = (flash_size - move_count*page_size + logical) % flash_size
 *   if (phys >= pos*page_size) phys += page_size   // skip dummy page
 *
 * This module detects such an image (validating the wl_config CRC32) and
 * translates logical byte addresses to physical file offsets.
 */

#ifndef WL_LAYER_H
#define WL_LAYER_H

#include <stdint.h>
#include <stdbool.h>
#include "../ip_driver/ip_driver.h"

/** wl_config_t as stored in the last config sector of the partition */
typedef struct {
    uint32_t start_addr;     /**< Partition-relative start address (0) */
    uint32_t full_mem_size;  /**< Total partition size in bytes */
    uint32_t page_size;      /**< WL page size (usually 4096) */
    uint32_t sector_size;    /**< Flash sector size (usually 4096) */
    uint32_t updaterate;     /**< Pos updates per dummy-page move */
    uint32_t wr_size;        /**< Size of one pos-update record */
    uint32_t version;        /**< WL layer version (2) */
    uint32_t temp_buff_size; /**< Scratch buffer size */
    uint32_t crc;            /**< CRC32 over the previous 32 bytes */
} WLConfig;

/** wl_state_t header as stored at addr_state1 / addr_state2 */
typedef struct {
    uint32_t pos;         /**< Current dummy page position (may be stale) */
    uint32_t max_pos;     /**< Number of positions = flash_size/page_size + 1 */
    uint32_t move_count;  /**< Full rotations of the dummy page */
    uint32_t access_count;
    uint32_t max_count;   /**< = updaterate */
    uint32_t block_size;  /**< = page_size */
    uint32_t version;
    uint32_t device_id;
    uint32_t reserved[7];
    uint32_t crc;         /**< CRC32 over the previous 60 bytes */
} WLState;

/** Runtime WL translation context */
typedef struct {
    bool enabled;         /**< true when a valid WL layer was detected */
    WLConfig cfg;
    WLState state;
    uint64_t flash_size;  /**< Usable (logical) data size in bytes */
    uint64_t addr_state1; /**< File offset of state copy 1 */
    uint64_t addr_state2; /**< File offset of state copy 2 */
    uint64_t addr_cfg;    /**< File offset of config */
} WLLayer;

/**
 * Detect and initialise the WL layer from a raw partition image.
 * @param wl     Pointer to WLLayer context (zeroed on non-WL images)
 * @param driver Opened IP driver used for raw byte access
 * @return 0 if a valid WL layer was found, 1 if the image is not
 *         wear-levelled (plain FAT image), -1 on I/O error
 */
int wl_layer_init(WLLayer* wl, IPDriver* driver);

/**
 * Translate a logical byte address to a physical file offset.
 * Valid only when wl->enabled is true and addr < wl->flash_size.
 * @param wl   WL context
 * @param addr Logical byte address inside the FAT volume
 * @return Physical byte offset in the image file
 */
uint64_t wl_layer_translate(const WLLayer* wl, uint64_t addr);

/**
 * CRC32 as computed by ESP-IDF crc32_le(0xFFFFFFFF, buf, len)
 * (reflected, poly 0xEDB88320, init 0, final XOR 0xFFFFFFFF... expressed
 * as ~crc32_update(~init)). Exposed for unit testing.
 */
uint32_t wl_crc32(const void* buf, uint32_t len);

#endif /* WL_LAYER_H */
